### PR TITLE
Upgrade to elixir-ls v0.7

### PR DESCRIPTION
**Pull request by bigardone**
👋🏼 Upgrades de language server to its latest version (v0.7) 😄 

https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.7.0

### CODE REVIEW

**Comment by gcauchon** [comment]
Now that Erlang/OTP `24.0.1` is out and Elixir `1.12.0` was released, the extension is broken when the codebase is upgraded. Configuring `elixir.pathToElixirLS` to `v0.7` works so I thing it's safe to merge the upgrade!

**Comment by amiralies** [comment]
Sorry for being late, i will upgrade soon

**Comment by gcauchon** [comment]
> Sorry for being late, i will upgrade soon

Considering the OTP `autoconf` fix was released yesterday and `1.12` released today, I don’t think you are "late". On the contrary, thank you for maintaining an extension I use it every day 😃

**Comment by amiralies** [comment]
Thank you for the PR. I've decided to do not keep language server source code in this repo so the submodule is removed. (the npm version still has bundled langauge server from elixir-ls repo's release page).
I may revert this change in future if i had time to automate the release.

**Comment by bigardone** [comment]
No worries, it is much better now! 🙌🏼

**Pull request closed without merging**
